### ISSUE TITLE
Use consistent naming for nodes/vertices

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_docs#101]
The specification is quite clear on how to call meta-level concepts:

* Entity: entity type in the dataset.
* Relationship: relationship type in the dataset.
* Attribute: attribute of an entity or relationship in the dataset

However, it is less clear on instance-level terminology:

* "node" and "edge" is used on occasions in query descriptions
* "vertex" is used (mostly in parts which I've written, e.g. 3.1 and 3.2.3)

Nodes are mostly referred to by their types, e.g. "a Forum" and not "a Forum node".

This is one of those things that do not really affect readability, but we should strive to get them right.

**Comment by ArnauPrat** [comment]
I always try to use node, except where it can be confused with a computing node given the context. Since this is not the case, I'd use node instead of vertex
