### ISSUE TITLE
BI Query 5 needs clarification

### ISSUE THREAD

**Issue by ArnauPrat** [ldbc/ldbc_snb_docs#103]
BiQ5:
```
Find the most popular Forums for a given Country , where the popularity of a Forum is measured
by the number of members that Forum has from the given Country .
For each member of the 100 most popular Forums , count the number of Posts they made in any
of those (most popular) Forums .
```
The top-100 most popular Forums are not deterministic. There can be forums with the same degree of popularity. This can happen at the edge of the top-100, so two different systems might return two different top-100 Forums, and hence, two different result sets.

An additional criteria for computing the top-100 must be selected in order to make this deterministic. For instance, the id of the forum.

**Comment by szarnyasg** [comment]
I agree, that seems a good way to make it deterministic. I’ll make the changes in the spec later today.
