### ISSUE TITLE
hasCreator arrow in the schema has the wrong direction

### ISSUE THREAD

**Issue by oskar-van-rest** [ldbc/ldbc_snb_docs#110]
In 2.3.2 Data Schema, the `hasCreator` arrow goes from Person to Message instead of the other way around.

**Comment by szarnyasg** [comment]
Thanks, well spotted! I fixed it on the `dev` branch.

**Comment by ArnauPrat** [comment]
Thanks Oskar for pointing this out. Since Gabor already fixed this, I close this issue.
