### ISSUE TITLE
Q16 fulfills chokepoint CP5.3?

### ISSUE THREAD

**Issue by ArnauPrat** [ldbc/ldbc_snb_docs#122]
CP 5.3 says:
```
This choke-point tests the ability of the execution engine to reuse sub-query results when two sub-queries are mostly identical. 
Some queries have almost identical sub-queries, where some of their internal results can be reused in both sides of the execution plan, thus avoiding to repeat computations.
```
When testing for reachability between node A and node B, if we found a set of nodes C that are also reachable from A, we can put these into a set S.
If in a later subquery we need to test between A and another node C already in the set S, we can skip the test for reachability so we are effectively reusing results from a previous subquery.

What do you think?

**Comment by szarnyasg** [comment]
Belatedly, but I agree. I added this change to the spec.
