### ISSUE TITLE
Errors in LDBC SNB data schema figure

### ISSUE THREAD

**Issue by jdellithorpe** [ldbc/ldbc_snb_docs#137]
In Figure 2.1: The LDBC SNB data schema:

* Message isLocatedIn Country: Missing cardinality labels (should be 1 country per Message, 0..* Messages per country).
* Forum hasModerator Person: A person can be the moderator of many forums, but schema currently says that a person can be the moderator of at most 1 forum (is this a bug in the data generator?).
* Person studyAt University: Missing cardinality labels (should be 1 University per Person, 0..* Persons per University).
* Person workAt Company: Missing cardinality labels (should be 0..* Companies per Person, 0..* Persons per Company).

**Comment by szarnyasg** [comment]
Thanks for raising this issue. It's surprising how many errors the [current schema](https://github.com/ldbc/ldbc_snb_docs/blob/master/figures/schema.pdf) has, even after [many previous fixes](https://github.com/ldbc/ldbc_snb_docs/commits/master/figures/schema.graphml). I checked the old schema and it seems that one bug was present back then as well (it defines `hasModerator` as `0..1`-`1`), while others were injected by yours truly.

![image](https://user-images.githubusercontent.com/1402801/46782345-310a2580-cd26-11e8-8ccb-ad53e1174d91.png)

I am not sure about what to do with the `studyAt` relation. Semantically, it makes sense to allow a person to be enrolled at multiple universities. However, the generator code clearly shows that multiple a person can have multiple `workAt` edges, but only a single `studyAt` edge.

https://github.com/ldbc/ldbc_snb_datagen/blob/a17456f37001dfbf0eed1fb8321a25db2ca3c4dd/src/main/java/ldbc/snb/datagen/serializer/PersonSerializer.java#L53-L75

**Comment by ArnauPrat** [comment]
So you propose to leave the studyAt relation as a 1 to many, but keep the serialization in a separate file as if we were producing this 1 to many relation, even if we currently produce a 1 to 1 one, am I right? If this is the case, it sounds good to me. We can always upgrade the generator to produce the 1 to many relationship if necessary, without breaking the rest of the stuff.

**Comment by szarnyasg** [comment]
I think you got the idea, but just to make sure: I propose leaving the `studyAt` reltation and its serialization file as _many-to-many_, even though we currently produce _many-to-one_ relations.

**Comment by szarnyasg** [comment]
Okay, this seems to be resolved by 8ef1a7b. Let us know if there are any further issues.

**Comment by szarnyasg** [comment]
It seems there were two more cardinality issues. The first, `likes`, spotted by @marci543, then I thoroughly checked the spec for inconsistencies with the figure and noticed the difference for `isSubclassOf`.
