### ISSUE TITLE
Data schema types don't match workload specifications

### ISSUE THREAD

**Issue by cstlee** [ldbc/ldbc_snb_docs#162]
The "result" types in many of the interactive workload specifications (Ch 4) don't seem to match the types specified in the data schema (Ch 2) even though they are specified to be "Raw (R)."  Is this intentional?  If so, are there specified conversions from one type to another?  Here are a few of the examples I've noticed so far:

- [IS 1] City.id specified as "32-bit Integer" in workload but as "ID" in schema
- [IS 2] Message.content specified as "String" in workload but as "Text" in schema
- [IS 4] Message.creationDate specified as "ID" in workload but as "DateTime" in schema

**Comment by szarnyasg** [comment]
@cstlee thanks for reporting this. These are clearly oversights (probably copy-paste errors), I just pushed a commit fixing them. Leaving this issue for a near-future revision of this.

**Comment by cstlee** [comment]
@szarnyasg Great! Thanks for the clarification and the fast response.

**Comment by szarnyasg** [comment]
Thanks, I revised the queries and fixed a number of errors on the way. I opened two followup issues, #173 (which should be simple) and #174 (which takes more effort).
