### ISSUE TITLE
query-cards/interactive-complex-read-01.tex not found

### ISSUE THREAD

**Issue by NeverMore2744** [ldbc/ldbc_snb_docs#178]
Hi, I clone the repository to my computer and use make to compile. However, I find that there is a missing file query-cards/interactive-complex-read-01.tex. And I find that the directory "query-cards" is empty. How can I solve the problem?

**Comment by szarnyasg** [comment]
Hi, check the [Generating query cards](https://github.com/ldbc/ldbc_snb_docs#generating-query-cards) section of the README. You'll need to install Pandoc and a few Python libraries.

**Comment by tetzank** [comment]
The makefile does not track the dependencies in the right way and therefore cannot run the commands in the correct order.

You must run `./generate-tex.py` first, either directly or with `make generate_query_cards`. Afterwards, you can build the document with `make` or `make texfot`.

**Comment by szarnyasg** [comment]
This is indeed annoying. I've fixed it and will push the fix in a moment. It isn't fully incremental because the `generate-tex.py` needs to collect the choke points from the TeX files. But that's just a minor inconvenience.
