### ISSUE TITLE
Converting SNB to RDF

### ISSUE THREAD

**Issue by kubajal** [ldbc/ldbc_snb_docs#179]
Hi,
I am curious if there is any preferred way to convert CSV data generated with LDBC SNB data generator into RDF? I suppose that it should be possible using e.g. this tool: https://www.w3.org/2013/csvw/wiki/CSV2RDF. Does anyone have experience with that?

I am aware that LDBC provides a separate benchmark for RDF engines (Semantic Publishing Network). Nonetheless I still would like to use SNB to feed my RDF engine.

Best regards,
Jakub

**Comment by szarnyasg** [comment]
Hi kubajal,

For the record, we have discussed this through email -- there is no preferred method to convert CSVs.

Currently, the best approach to generate the data twice, once with the CSV serializer and once with the Turtle serializer. The latter is currently only supported on the `stable` branch (v3.x) of the data generator.

Gabor

**Comment by kubajal** [comment]
Yes, thank you!
