### ISSUE TITLE
Do we simulate something going viral?

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_docs#180]
We have bursty (flashmob) events and "unfriending" operations. Do we simulate a post going viral or a similar event?

**Comment by jackwaudby** [comment]
So we simulate flashmob events, which are spikes in posts around a specific tag. The Myers et al. Twitter paper identifies bursts in friendship and unfriending, but as we don't model the bursts in friendships, we don't model the bursts in unfriendships (future work perhaps). We don't simulate a viral post specifically, it's not clear to me how we would capture a viral post, as we don't have similar concepts to shares or retweets, which is how                                                                                                                                                posts go viral in Twitter and Facebook. One approach could be to mark specific posts as "viral posts" and have them receive a larger portion of comments and likes.
