### ISSUE TITLE
Are there publicly available LDBC SNB Interactive Worklad queries in Cypher or SPARQL?

### ISSUE THREAD

**Issue by kubajal** [ldbc/ldbc_snb_docs#182]
Hi,
in the _The LDBC Social Network Benchmark: Interactive Workload_ paper from 2015, it is said that ` The base definition of the queries is in English, from the LDBC website[4](ldbcouncil.org/developer/snb) one can find query definitions in SPARQL, Cypher and SQL, as well as API reference implementations for neo4j and Sparksee.` Did this claim become obsolete, ie. did the mentioned queries disappear from that website in the meantime?
From what I understood until now it was up to the reader to write down queries for the graph databases that they targeted. Were there any efforts on the LDBC side or by the community to maintain queries expressed in popular graph query languages like Cypher or SPARQL? I assume it would involve reasonable effort as the SNB dataset schema evolves and eg there are new features being added to Cypher Query Language.

Best regards,
Jakub

**Comment by szarnyasg** [comment]
Hi @kubajal, you can find both Cypher and SPARQL implementations on the `stable` branch of the implementations repository:
- https://github.com/ldbc/ldbc_snb_implementations/tree/stable/cypher/queries
- https://github.com/ldbc/ldbc_snb_implementations/tree/stable/sparql/queries

**Comment by szarnyasg** [comment]
Apologies for the brevity yesterday - I just fired off the comment with the links as quickly as I could. Today I've looked into this issue in more detail and noticed that the SNB repositories are (somewhat inexplicably) not linked in the SNB specification.

I have amended now this. Let me know if you need anything else.

**Comment by kubajal** [comment]
Hi, that solves my problem, thanks! :) That's great that the LDBC team provides those queries.
