### ISSUE TITLE
Unclear specification versions

### ISSUE THREAD

**Issue by cw00dw0rd** [ldbc/ldbc_snb_docs#203]
In the ReadMe, you link to the 0.4.0-SNAPSHOT at the very [top](https://github.com/ldbc/ldbc_snb_docs#ldbc-snb-documentation).
However, [two sections down ](https://github.com/ldbc/ldbc_snb_docs#ldbc-snb-documentation)you link to 0.3.3 and I have come across this version elsewhere as well. Should the existing links be updated to reference the SNAPSHOT or is 0.3.3 still considered more _correct_? Or is there no functional difference between the two, just minor changes?

Mostly looking for clarification on the one I should be using but happy to fix links if appropriate.

**Comment by szarnyasg** [comment]
@cw00dw0rd thanks for reaching out. I clarified the README.

It basically boils down to which workload you use:
* Interactive: its specification is solid and the two PDFs are 99.9% the same, the only differences will be typo fixes and clarifications.
* BI workload: the latest SNAPSHOT is recommended.

Let me know if you have further questions.
