### ISSUE TITLE
Inconsistent note of edge weight on BI19.

### ISSUE THREAD

**Issue by ErvinXie** [ldbc/ldbc_snb_docs#225]
![截屏2022-11-07 15 11 32](https://user-images.githubusercontent.com/29942298/200246959-bd147804-5464-494f-b73e-b3dfe9503157.png)
The definition of edge weight here seems ambiguous. I guess the note and the annotation on graph is not updated together with the specification. My spec file version is 2.2.0.

**Comment by szarnyasg** [comment]
Good catch – thanks for raising this issue. The fix is incoming in a minute and I'll upload a new version to arXiv later this week.
