### ISSUE TITLE
Add statistics Interactive v1.0 updates

### ISSUE THREAD

**Issue by GLaDAP** [ldbc/ldbc_snb_docs#228]
The interactive v1.0 update stream statistics are missing in the documentation, only the totals are provided. Below are statistics derived from the numpart-1 files for scale factors up to SF30. Up to SF1000 still needs to be done.

| T                            | C | Type                 | SF1     | SF3     | SF10     | SF30      | SF100 | SF300 | SF1000 |
|------------------------------|---|----------------------|---------|---------|----------|-----------|-------|-------|--------|
| I                            | E | Add Like to Post     | 494410  | 1460471 | 4875874  | 14378128  |       |       |        |
| I                            | E | Add Like to Comment  | 460487  | 1450891 | 5210730  | 16114277  |       |       |        |
| I                            | N | Add Forum            | 19757   | 49223   | 131439   | 330288    |       |       |        |
| I                            | E | Add Forum Membership | 1566914 | 4874316 | 16647977 | 51095793  |       |       |        |
| I                            | N | Add Post             | 229614  | 592875  | 1655168  | 4304447   |       |       |        |
| I                            | N | Add Comment          | 490328  | 1372420 | 4414427  | 12588582  |       |       |        |
| I                            | E | Add Friendship       | 40124   | 122714  | 431916   | 1304053   |       |       |        |
| I                            | N | Add Person           | 1108    | 2672    | 7355     | 18570     |       |       |        |
| Total insert node operations |   |                      | 740807  | 2017190 | 6208389  | 17241887  |       |       |        |
| Total insert edge operations |   |                      | 2561935 | 7908392 | 27166497 | 82892251  |       |       |        |
| TOTAL                        |   |                      | 3302742 | 9925582 | 33374886 | 100134138 |       |       |        |

**Comment by szarnyasg** [comment]
I'm running a script to calculate these now. Where are the totals in the document? I took a glance but was unable to locate them.

**Comment by GLaDAP** [comment]
The totals are shown in Appendix B, B1 Number of entities for SNB Interactive v1.0 (p.144)

**Comment by szarnyasg** [comment]
Thanks! I was looking for the total of the entities inserted by the update streams. I'll add the table with the update stream statistics once the script finished.
