### ISSUE TITLE
add more documentation related to the import process, the format of files, etc.

### ISSUE THREAD

**Issue by alexaverbuch** [ldbc/ldbc_snb_docs#29]
We say very little (almost nothing) about the format of generated .csv files.
We say nothing about how to deal with the optional parameters like Message.content, Post.imageFile, Post.language, etc.
In general, the data import phase is very neglected.
We need to cover this material in an upcoming spec release.

**Comment by szarnyasg** [comment]
I clarified a lot of this in recent commits: all CSV formats, update streams and substitution parameters are now defined in tables. Also, in 12ced6caca047909fa31c69c3aa8d30696a149c3, I clarified that using NULLs is permitted when importing the data.
