### ISSUE TITLE
consider documenting Person.email and Person.speaks as separate entities, rather than putting them inside Person

### ISSUE THREAD

**Issue by alexaverbuch** [ldbc/ldbc_snb_docs#30]
At present Person.email and Person.speaks are documented in the UML diagram as attributes of Person, however these could be seen as separate entities.
Languages especially, as they are shared among multiple persons.
It seems a little inconsistent to not do so.

**Comment by szarnyasg** [comment]
@alexaverbuch @ArnauPrat it seems to me that the decision was to keep `email` and `speaks` as attributes. Can we close this issue?

**Comment by ArnauPrat** [comment]
Yes, let's keep as is right now. Such a change now would be troublesome
