### ISSUE TITLE
more documentation regarding the practical parts of validation

### ISSUE THREAD

**Issue by alexaverbuch** [ldbc/ldbc_snb_docs#33]
we should document where the validation/debugging (a smaller version of validation?) datasets are.
some will go in ldbc_driver documentation, but perhaps we should write a little more about how to get started, how to debug an implementation, where to find a small/toy dataset (and validation parameters) to do that with, etc.

**Comment by ArnauPrat** [comment]
since this is tightly related to the driver, why not put it in the driver's github page?

**Comment by szarnyasg** [comment]
Actually, what are the debugging datasets? How do I generate them?

**Comment by szarnyasg** [comment]
As a followup to this issue, we had lengthy discussions with @alexaverbuch in 2017. I believe this aspect of SNB is now fairly well-documented so I'm closing this as resolved.
