### ISSUE TITLE
Not clear if all comments should always be in reply to something

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_snb_docs#45]
In the schema diagram cardinality of replyOf edge is 0..\* so comments may not be in reply to anything. 
but in update query 7 you have to have either a replyOf Post or a reply of comment. Also, what happens if both are -1? logic gets circular at some point...

**Comment by szarnyasg** [comment]
This seems to have been fixed some time ago:

![image](https://user-images.githubusercontent.com/1402801/28821593-51a0de64-76b6-11e7-80d5-4adbae1aa1f2.png)

However, the current doc is not entirely consistent yet. Let's fix it.
