### ISSUE TITLE
Clarification of query 12 needed regarding what tags to output

### ISSUE THREAD

**Issue by ArnauPrat** [ldbc/ldbc_snb_docs#47]
Hi @alexaverbuch and @tomersagi

According to query 12's description, the list of tags of posts to output in the result set seems to not be restricted to only those present in the input tagclass or any subclass. However, in the validation dataset provided at ldbc-dev, it seems that only those tags belonging to that subset are actually output, while the rest are omitted. Should this be clarified in the query's description or is the validation set incorrect? What do you think?

Thanks

Arnau

**Comment by tomersagi** [comment]
Hi,
As you know, I think that the query definitions are not well defined and that we should use some extension of relational calculus to define them.
Barring that, the cypher reference implementation provided as part of the spec is to be regarded as the golden standard.
Therefore, the tags should be those in the posts retrieved.
Tomer
