### ISSUE TITLE
Clarification required for Short Query 2

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_snb_docs#48]
Hi,
From the description (in tex) it isn't clear whether to return messages which are not replies to another message and if we are to return them, what values to put in the original message fields. 
Thanks
Tomer

**Comment by alexaverbuch** [comment]
From:
http://wiki.ldbcouncil.org/display/TUC/Interactive+Workload
The description is:
```
Given a start Person, retrieve the last 10 Messages (Posts or Comments) created by that user.
For each message, return that message, the original post in its conversation, and the author of that post.
Order results descending by message creation date, then descending by message identifier
```
I haven't read the spec tex. What does it say? Is it the same? And what exactly is unclear?

**Comment by tomersagi** [comment]
Its the same. 
Given a message, there may not be an original post in its conversation. It may be singular / the beginning of the conversation. What should we return in this case?

**Comment by alexaverbuch** [comment]
There is always an original Post, every conversation starts with a Post and then proceeds as a tree of Comments. If the Message is a Post, then the original Post will be the same Message, i.e., that Message will appear twice in the result.
Does that make sense?

**Comment by tomersagi** [comment]
Sure, I recommend describing this scenario in the query description.

**Comment by alexaverbuch** [comment]
We could, but why is it necessary? 
Doesn't the current description capture what I wrote above. Phrased differently, would you mind explaining what alternate interpretation could result from the current description?

**Comment by tomersagi** [comment]
I understood the term "original post in its conversation" to be relevant only for messages which are replies to other messages. I would return null / empty strings for posts that don't have an original post in their conversation.

**Comment by alexaverbuch** [comment]
@tomersagi does this sound ok?
```
Given a start Person, retrieve the last 10 Messages (Posts or Comments) created by that user.
For each message, return that message, the original post in its conversation, and the author of that post.
If any of the Messages is a Post, then the original Post will be the same Message, i.e., that Message will appear twice in that result.
Order results descending by message creation date, then descending by message identifier
```
@ArnauPrat if Tomer approves it, would you mind modifying the description to what I wrote above?

**Comment by tomersagi** [comment]
Sounds right

**Comment by ArnauPrat** [comment]
done
