### ISSUE TITLE
Suggesting clarification of short query 6

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_snb_docs#49]
"Given a Message (Post or Comment), retrieve the Forum that contains it and the Person that moderates that forum." add: "Since comments are not directly contained in forums, for comments, return the forum containing the original post in the thread which the comment is replying to. "

**Comment by alexaverbuch** [comment]
+1
@ArnauPrat would you mind updating the TeX please?
I'll take care of Confluence
Here's the updated text:
```
Given a Message (Post or Comment), retrieve the Forum that contains it and the Person that moderates that forum. 
As comments are not directly contained in Forums, for Comments return the Forum containing the original Post of the thread which the Comment is replying to.
```

**Comment by szarnyasg** [comment]
The current doc contains the updated version, so closing this as fixed.
