### ISSUE TITLE
Q10 definition of query problem

### ISSUE THREAD

**Issue by mirkospasic** [ldbc/ldbc_snb_docs#53]
Persons are filtered by their birthday: "who were born on or after the 21st of a given month (in any year) and before the 22nd of the following month". Maybe it is better to delete words "on or", in order not to count 21st twice.

**Comment by alexaverbuch** [comment]
good point, I agree.
it won't get changed now, but let's include this in the next set of workload changes, after the review

**Comment by szarnyasg** [comment]
The doc still says "on or after the 21st of a given month". What should we do about this @ArnauPrat @alexaverbuch ?

**Comment by ArnauPrat** [comment]
According to my implementation which was validated against @alexaverbuch  one, we kept the "on or". I'd leave it as is right now.

**Comment by szarnyasg** [comment]
Cool, so we can close this as well =).
