### ISSUE TITLE
Typo: SNB/IW Q3 short likely expects a DateTime for the creationDate

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_snb_docs#56]
Hello, I believe there is a small typo in the [docs](https://github.com/ldbc/ldbc_snb_docs/blob/master/LDBC_SNB_v0.2.3.pdf). In the description of the short query no.3 pp.30, the type of creationDate should be probably a DateTime, as it is the same type of the underlying attribute.

**Comment by ArnauPrat** [comment]
Thanks  @whatsthecraic 
I've fixed the typo in the sources. The fix will be visible on the next release.
