### ISSUE TITLE
SNB I/W: smallish typos

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_snb_docs#57]
Just reporting a couple of typos from the doc:
- In short query #7, it is implied the result set is also expecting a boolean whether the authors of the post and of the comment are friends. From the used notation it also seems that the result set requires the author of the post instead of the author of the comment.
- In the specification's description of the Update #4, the moderator should not be a collection.

**Comment by szarnyasg** [comment]
> In the specification's description of the Update #4, the moderator should not be a collection.

Correct, as a Forum has precisely one moderator.

**Comment by szarnyasg** [comment]
> In short query #7, it is implied the result set is also expecting a boolean whether the authors of the post and of the comment are friends. From the used notation it also seems that the result set requires the author of the post instead of the author of the comment.

Indeed, it makes more sense to return the author of each comment. I also introduced the `knows` Boolean attribute to flag whether the authors are friends.
