### ISSUE TITLE
Update query specifications

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_docs#61]
@ArnauPrat in the Update Query Descriptions, I think this should be `Forum-hasMember->`...

> 5. Add Forum Membership
> • Description: Add a Forum membership to the social network.
> • Parameters:
> Person.id ID
> Person-hasMember->Forum.id ID
> Person-hasMember->.joinDate DateTime

**Comment by szarnyasg** [comment]
I investigated it a bit more and it seems that it's not the edge direction, but the parameters that are swapped. So it should be:

> Forum.id ID
> Forum-hasMember->Person.id ID
> Forum-hasMember->.joinDate DateTime

**Comment by szarnyasg** [comment]
I found another minor issue in update 6:

> 6. Add Post
> • Description: Add a Post to the social network.
> • Parameters:
> Post.id ID
> Post.imageFile String
> Post.creationDate DateTime
> Post.locationIp String
> Post.browserUsed String
> Post.language String
> Post.content Text
> Post.length 32-bit Integer
> Post-hasCreator->Person.id ID
> Forum-containerOf->Post.id ID --> this should be Forum.id-containerOf->Post
> Post-isLocatedIn->Country.id ID
> {Post-hasTag->Tag.id} {ID}

**Comment by ArnauPrat** [comment]
Thanks @szarnyasg 
You are right, these are errors that must be fixed.
