### ISSUE TITLE
How to handle aggregations in the query specifications

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_docs#64]
Most BI queries have some aggregations. These are often simple operations (count this, sum that), but they can get more complicated, e.g. [BI query 5](https://github.com/ldbc/ldbc_snb_docs/blob/19133fd531e1345e724cc56fa0c64229ba6f8a1a/query-specifications/bi-read-05.yaml) aggregates, takes the top 100 values and aggregates again.

The specification currently contains a `group:` key which lists the aggregation values, lifted from the [wiki page](http://wiki.ldbcouncil.org/display/TUC/Business+Intelligence+Workload). However, this is quite limited as it only lists the grouping keys for the _last_ aggregation. So this could use some improvements. Ideas:

1. Drop `group` and let users figure out the grouping, based on the textual specification (and maybe get a hint from the graphical patterns).
2. Keep `group`, but introduce multiple levels. For example, Bi query 5 would get something like this:
   ```
   group:
     - ["country", "forum"] # for counting forum members
     - ["person"] # for counting posts
   ```
3. Keep `group` as it is. It is sloppy, but still gives users a hint on what to aggregate on.

@alexaverbuch @ArnauPrat @MarcusParadies

**Comment by ArnauPrat** [comment]
My opinion, and I think I already stated it during our meetings, is that the group field is confusing and replicates information that should be present in the description only (otherwise we open the door for inconsistency errors between the two). Thus, I vote for dropping such field (as a side effect, will make the query specifications shorter :P)

**Comment by alexaverbuch** [comment]
I agree with @ArnauPrat 
In addition, once we have SQL, SPARQL, Cypher, PGQL examples it will become even more clear to implementers
