### ISSUE TITLE
Inconsistencies for parameter types

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_docs#73]
TagClasses are sometimes represented with their ids and sometimes with their names. While both approaches work, is this intentional? If so, we should use different names (e.g. `tagClassName` vs. `tagClassId`). If not, we should agree in a unified approach.

```
bi-read-04.yaml
11:  - name: tagClass
12-    type: 32-bit Integer

bi-read-09.yaml
12-parameters:
13:  - name: tagClass1
14-    type: 32-bit Integer
15:  - name: tagClass2
16-    type: 32-bit Integer

bi-read-16.yaml
18:  - name: tagClass
19-    type: String

bi-read-19.yaml
20:  - name: tagClass1
21-    type: 32-bit Integer
22:  - name: tagClass2
23-    type: 32-bit Integer

bi-read-20.yaml
9:  - name: tagClasses
10-    type: String[]

bi-read-24.yaml
10:  - name: tagClass
11-    type: String
```

FWIW, the substitution parameter generator always generates strings:

```
q4_param.txt
1:tagClass|country
2-MusicalArtist|Netherlands

q9_param.txt
1:tagClass1|tagClass2|threshold
2-BaseballPlayer|ChristianBishop|200

q19_param.txt
1:date|tagClass1|tagClass2
2-599634000000|MusicalArtist|OfficeHolder

q24_param.txt
1:tagClass
2-Single
```

@mkaufmann @ArnauPrat @alexaverbuch @MarcusParadies

**Comment by szarnyasg** [comment]
Same goes for `country`.

**Comment by ArnauPrat** [comment]
You should take a look at what the driver expects and whether this is just a documentation issue or this change could affect the driver. Basically, the driver uses results returned by complex read queries to issue short reads. If we change the parameters, there could be a mismatch between what the driver have and what the queries expect as parameters. Do you understand what I mean?

**Comment by szarnyasg** [comment]
The driver is tested with the substitution parameters, so the types of the param files should reflect those in the driver. Let me check this manually though.

**Comment by szarnyasg** [comment]
I believe these are all fixed now. Will reopen if necessary.
